<?php

$title = 'Add new album';
$this->headTitle($title);

?>

<?php

$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary btn-sm btn-block');

$form->setAttribute( 'action', $this->url('album', ['action' => 'add']) );
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="col-md-5 card mx-auto border-0 shadow py-4">
    <div class="card-header bg-transparent border-0 p-0">
    <h1 class="text-center"><?= $this->escapeHtml($title) ?></h1>
    </div>
    <div class="card-body">

        <div class="form-group">
            <?= $this->formLabel($album) ?>
            <?= $this->formElement($album) ?>
            <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
        </div>
        
        <div class="form-group mb-md-4">
            <?= $this->formLabel($artist) ?>
            <?= $this->formElement($artist) ?>
            <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
        </div>

        <?php
        echo $this->formSubmit($submit);
        echo $this->formHidden($form->get('id'));
        echo $this->form()->closeTag();
        ?>

    </div>
</div>