<?php

$title = 'Delete album';
$url = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);

?>

<div class="col-md-5 card border-0 shadow mx-auto">

    <div class="card-header bg-transparent border-0">
        <h1 class="text-center"><?= $this->escapeHtml($title) ?></h1>
    </div>

    <div class="card-body">
        <p>
            Are you sure that you want to delete
            <b>
                "<?= $this->escapeHtml( $album->title ) ?>"
            </b> by
            <b>
                "<?= $this->escapeHtml( $album->artist ) ?>"
            </b> ?
        </p>
        <form action="<?= $url ?>" method="POST">
            <div class="d-flex form-group mt-5">
                <input type="hidden" name="id" value="<?= (int) $album->id ?>">
                <input type="submit" class="btn btn-danger mx-5" name="del" value="Yes" style="flex-grow: 1;">
                <input type="submit" class="btn btn-success mx-5" name="del" value="No" style="flex-grow: 1;">
            </div>
        </form>
    </div>
</div>
